### PR TITLE
added petsc import to simplify import structure

### LINKED ISSUE #66: Error while importing MassMumps Solver
Hi,
I am trying to import the petsc interface MassMUMPS solver by following the tutorial. But it throws an error saying it cannot be imported.
I think the problem is the __init__.py file inside the petsc4py folder is empty. If we add the following line, this will resolve the error I suppose.
`from .solvers import MassSolverMUMPS`

### PR DESCRIPTION
**Pull request by Chiffafox**
Quick fix to allow PETSc solver import to be done the same way as all other GGCE objects. Merging this will close #66.

### CODE REVIEW

**Comment by Chiffafox** [comment]
Wow, @x94carbone any idea what happened with those tests?

**Comment by x94carbone** [comment]
@Chiffafox ya the serial tests are not supposed to require `pestsc` 😁

Petsc is only installed after the serial checks pass.

**Comment by Chiffafox** [comment]
Right, fair enough! Did I accidentally change something to make serial tests require `petsc`? I just added a one-liner to __init__.py so petsc Solver can be imported in the same way as System, Model etc.

**Comment by x94carbone** [comment]
No but you made the default version of `ggce` inherently dependent on `petsc`! Adding that import in the `__init__` means that any time someone uses `ggce` they will be required to have `petsc` in their python path.

**Comment by x94carbone** [comment]
Well the long import should work in principle. If we want to simplify this in the `__init__` we probably need a try/except ImportError there. That should do the trick.

**Comment by x94carbone** [comment]
@Chiffafox lets see if this passes the checks.

While we're at it, can you
- Use the `--runslow` flag in the CI loop (something I forgot to do for a while)
- Fix the Flake8/Black issues?

Thanks!

**Comment by Chiffafox** [comment]
> @Chiffafox lets see if this passes the checks.
> 
> While we're at it, can you
> 
>     * Use the `--runslow` flag in the CI loop (something I forgot to do for a while)
> 
>     * Fix the Flake8/Black issues?
> 
> 
> Thanks!

Done and done. Should be good once the checks go through.

**Comment by x94carbone** [comment]
@Chiffafox thanks! I also disabled the stupid code quality check (I think) that will fail the test. Though we should probably try to get the code quality back to an "A"... 😁

**Comment by Chiffafox** [comment]
> @Chiffafox thanks! I also disabled the stupid code quality check (I think) that will fail the test. Though we should probably try to get the code quality back to an "A"... 😁

We sure should! How come we took a hit on that? I didn't think I changed anything that would downgrade it by a whole letter grade...

**Comment by x94carbone** [comment]
@Chiffafox I honestly have no idea. It checks a lot of things... you should be able to see if you click the badge in the README.

**Comment by Chiffafox** [comment]
I see. Okay, well, it is complaining that
>  Code Style '.executors.petsc4py.solvers.MassSolverMUMPS' imported but unused (F401) 
which is unfair because it _is_ used, obviously -- just not in a manner the checker can easily see.

It also doesn't like pickle because of security implications -- raises this a lot.
>  Security Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible security issue. 

I toyed for a bit with creating a class importer based on pickle that would only open certain types of files -- but not sure if this would fix the issue. Probably wouldn't be happy until we switched to HDF5 or something.

Then it has some issues with stuff that is sitting in legacy -- that's fine, it will be gone once we're done with it.

So I think our code is quite good -- the checker is just really unhappy about pickle.

**Comment by x94carbone** [comment]
@Chiffafox ok sounds good. Btw, I think we need to remove `--runslow` 😁

Tests take longer than 6 hours I guess, which appears to be the limit for each individual _job_ in GitHub actions! It does appear we might be able to hack around this by splitting the CI into different jobs though: https://stackoverflow.com/questions/68187987/github-actions-job-timeout.

What do you think?

**Comment by Chiffafox** [comment]
Right, this makes sense. The subset of "precise" tests included under `--runslow` are very slow -- depending on the architecture and available cores, they can take days. This is simply by the nature of the test. If we want to do a calculation to compare against stored DMRG data, which is the "real test", it has to be run at M = 3, N = 9, M_t = 3, N_t = 5. And this is an expensive calculation, even if comparing only at a few points. 

I should note that we have other finite T tests that give us confidence in the approach, like the T = 0 vs T = 1e-6 test. Also, I already include a "dumbed down" version of the precise test -- I generated and hard-coded data for small cloud configuration with a version that passes the test (I tested this on my HPC) against the full DMRG calculation. So we already run a small cloud test against verified data. This runs quickly and was already included in the pipeline.

I looked at the post you linked but I don't think our problem is of the same scope: they are talking about a 10 hour limit, whereas we are thinking about days or maybe even a week with GitHub level of resources.

Overall, I think we should clearly demarcate this test as something that users should only run locally on their HPC configurations, and remove the `--runslow` flag so it doesn't kill our GitHub action.

**Comment by x94carbone** [comment]
@Chiffafox that sounds fine to me, thank you!

**Comment by Chiffafox** [comment]
Sounds good! Just pushed a new commit without `--runslow` -- once the tests go through, should be good to merge and resolve #66.

**Review by x94carbone — APPROVED** [review]
Solid, I'm good to merge. If you approve pull the trigger (and **rebase**)!

**Pull request merged**
