### PR TITLE
sf initial edits

### PR DESCRIPTION
**Pull request by Chiffafox**
I wanted to start a PR for docs, so we can have some intermediate discussions here about the docs progress.

So far I am thinking that in installation, we can roll over all the "institutional" instructions into one -- in practice I have also been installing using pip. We can just two sets, one for installing with pip and one for installing from source (I will try to test the from source stuff again).

Other than that, I can confirm that the WSL installation works okay, it is not that experimental. 

Finally, I was wondering if we should provide some examples of setting logger to debug and some such, i.e. using the context manager? I am a bit hazy on that personally.

### CODE REVIEW

**Comment by x94carbone** [comment]
@Chiffafox looks fantastic, should I merge?

**Comment by Chiffafox** [comment]
Yeah let's do it! The only "core" tutorial still missing is the finite t one, I'll try to get to that one soon -- will open another PR for that.

**Comment by Chiffafox** [comment]
Hey @x94carbone, still don't see the updated docs (specifically tutorials) on the mainpage (on the right), even though all the updated source files are now part of master -- do we need to do something extra to start hosting the new version?

**Comment by x94carbone** [comment]
@Chiffafox ya I didn't deploy yet. I'll tag this later and it will automatically push the docs 👍

**Pull request merged**
